/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/appinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about available modules */
        get: operations["get-appinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appinfo-unapproved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about unapproved modules */
        get: operations["get-unapproved-appinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appinfo-unapproved/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve an unauthorized module */
        post: operations["approve-module"];
        /** Disallow an unauthorized module */
        delete: operations["disallow-module"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appinfo/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh available modules */
        post: operations["refresh-appinfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download backup
         * @description Download a snapshot of your system, including module configurations, settings, and past events. Sensitive data will not be included.
         */
        get: operations["download-backup"];
        put?: never;
        /** Restore backup */
        post: operations["restore-backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configs of running modules */
        get: operations["get-configs"];
        put?: never;
        /** Add or update a module */
        post: operations["set-config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a module */
        delete: operations["delete-module"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a module */
        post: operations["start-module"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a module */
        post: operations["stop-module"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listen to events */
        get: operations["listen-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listen to a specific event */
        get: operations["listen-event"];
        put?: never;
        /**
         * Emit event
         * @description Emit an event and optionally open a stream to listen for a response.
         */
        post: operations["emit-event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about Teldio Fabric */
        get: operations["get-info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get changelog */
        get: operations["get-changelog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get theming data */
        get: operations["get-theme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about the latest update */
        get: operations["get-update-info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/update/installer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest installer */
        get: operations["get-latest-installer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current license */
        get: operations["get-license"];
        put?: never;
        /** Register a license */
        post: operations["post-license"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register online */
        post: operations["register-online"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a license request file */
        get: operations["get-license-request"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["post-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["post-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set current user password */
        put: operations["set-user-password"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proxies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register proxy */
        post: operations["register-proxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart */
        post: operations["restart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh session */
        post: operations["refresh-session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set host and port */
        post: operations["set-host-and-port"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get users */
        get: operations["get-users"];
        put?: never;
        /** Create user */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["delete-user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change user password */
        put: operations["change-user-password"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change user role */
        put: operations["change-user-role"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Change-user-passwordRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Change-user-passwordRequest.json
             */
            readonly $schema?: string;
            newPassword: string;
        };
        "Change-user-roleRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Change-user-roleRequest.json
             */
            readonly $schema?: string;
            role: string;
        };
        Config: {
            config?: {
                [key: string]: unknown;
            };
            configSecrets?: string[] | null;
            description?: string;
            disabled?: boolean;
            id: string;
            module: string;
            proxy?: components["schemas"]["ProxyOptions"];
            service?: boolean;
            /** @enum {string} */
            status: "disabled" | "stopped" | "offline" | "online";
            statusReason: string;
            title?: string;
        };
        ConfigInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ConfigInput.json
             */
            readonly $schema?: string;
            config: {
                [key: string]: unknown;
            };
            description?: string;
            id?: string;
            module: string;
            start?: boolean;
            title?: string;
        };
        Cookie: {
            Domain: string;
            /** Format: date-time */
            Expires: string;
            HttpOnly: boolean;
            /** Format: int64 */
            MaxAge: number;
            Name: string;
            Partitioned: boolean;
            Path: string;
            Quoted: boolean;
            Raw: string;
            RawExpires: string;
            /** Format: int64 */
            SameSite: number;
            Secure: boolean;
            Unparsed: string[] | null;
            Value: string;
        };
        "Create-userRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-userRequest.json
             */
            readonly $schema?: string;
            password: string;
            role: string;
            username: string;
        };
        DemoLicense: {
            /** Format: date-time */
            expiry: string;
        };
        DevelopmentLicense: {
            /** Format: date-time */
            expiry: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        EventInfo: {
            $anchor?: string;
            $comment?: string;
            $defs?: {
                [key: string]: components["schemas"]["Schema"];
            };
            $dynamicRef?: string;
            $id?: string;
            $ref?: string;
            $schema?: string;
            additionalProperties?: components["schemas"]["Schema"];
            allOf?: components["schemas"]["Schema"][] | null;
            anyOf?: components["schemas"]["Schema"][] | null;
            const?: unknown;
            contains?: components["schemas"]["Schema"];
            contentEncoding?: string;
            contentMediaType?: string;
            contentSchema?: components["schemas"]["Schema"];
            default?: unknown;
            dependentRequired?: {
                [key: string]: string[] | null;
            };
            dependentSchemas?: {
                [key: string]: components["schemas"]["Schema"];
            };
            deprecated?: boolean;
            description?: string;
            else?: components["schemas"]["Schema"];
            enum?: unknown[] | null;
            examples?: unknown[] | null;
            /** Format: double */
            exclusiveMaximum?: number;
            /** Format: double */
            exclusiveMinimum?: number;
            format?: string;
            if?: components["schemas"]["Schema"];
            items?: components["schemas"]["Schema"];
            /** Format: int64 */
            maxContains?: number;
            /** Format: double */
            maximum?: number;
            /** Format: int64 */
            maxItems?: number;
            /** Format: int64 */
            maxLength?: number;
            /** Format: int64 */
            maxProperties?: number;
            /** Format: int64 */
            minContains?: number;
            /** Format: double */
            minimum?: number;
            /** Format: int64 */
            minItems?: number;
            /** Format: int64 */
            minLength?: number;
            /** Format: int64 */
            minProperties?: number;
            /** Format: double */
            multipleOf?: number;
            name: string;
            not?: components["schemas"]["Schema"];
            oneOf?: components["schemas"]["Schema"][] | null;
            pattern?: string;
            patternProperties?: {
                [key: string]: components["schemas"]["Schema"];
            };
            prefixItems?: components["schemas"]["Schema"][] | null;
            properties?: components["schemas"]["OrderedMapStringSchema"];
            propertyNames?: components["schemas"]["Schema"];
            readOnly?: boolean;
            reply?: components["schemas"]["Schema"];
            required?: string[] | null;
            then?: components["schemas"]["Schema"];
            title?: string;
            type?: string;
            uniqueItems?: boolean;
            writeOnly?: boolean;
        };
        GetInfoBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetInfoBody.json
             */
            readonly $schema?: string;
            accessFromLoopback: boolean;
            canRegisterOnline: boolean;
            managerHost: string;
            /** Format: int64 */
            managerPort: number;
            showInitialiseFlow: boolean;
            version: string;
        };
        GetLicenseResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetLicenseResponseBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            configuredModules?: number;
            /** Format: date-time */
            expiry?: string;
            license?: components["schemas"]["LicenseClaims"];
            licenseError?: string;
            licenseWarning?: string;
            shortError?: string;
        };
        GetMeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetMeBody.json
             */
            readonly $schema?: string;
            permissions?: ("modules:manage" | "settings:manage" | "settings/users:manage" | "events:manage" | "updates:manage")[] | null;
            role: string;
            /** Format: int64 */
            sessionExpiresAt: number;
            username: string;
        };
        GetUsersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetUsersOutputBody.json
             */
            readonly $schema?: string;
            users: components["schemas"]["UserDetails"][] | null;
        };
        Info: {
            config?: components["schemas"]["Schema"];
            description?: string;
            emits?: components["schemas"]["EventInfo"][] | null;
            listens?: components["schemas"]["EventInfo"][] | null;
            name: string;
            queries?: components["schemas"]["Queryable"][] | null;
            service?: boolean;
            title: string;
            version?: string;
        };
        LicenseClaims: {
            id: string;
            /** Format: date-time */
            issued: string;
            v1?: components["schemas"]["LicenseV1"];
            /** Format: int64 */
            version: number;
        };
        LicenseV1: {
            demo?: components["schemas"]["DemoLicense"];
            development?: components["schemas"]["DevelopmentLicense"];
            hardwareId: string;
            perpetual?: components["schemas"]["PerpetualLicense"];
            storedToken: string;
        };
        OrderedMapStringSchema: Record<string, never>;
        PerpetualLicense: {
            /** Format: int64 */
            configuredModuleLimit: number;
            /** Format: date-time */
            supportExpiry: string;
        };
        "Post-licenseRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Post-licenseRequest.json
             */
            readonly $schema?: string;
            license: string;
        };
        "Post-loginRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Post-loginRequest.json
             */
            readonly $schema?: string;
            password: string;
            username: string;
        };
        PostConfigBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostConfigBody.json
             */
            readonly $schema?: string;
            id: string;
        };
        ProxyOptions: {
            sidebarItem?: components["schemas"]["SidebarItem"];
            url: components["schemas"]["URL"];
        };
        Queryable: {
            description?: string;
            input?: components["schemas"]["Schema"];
            mediaType: string;
            name: string;
            title?: string;
        };
        "Register-onlineRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Register-onlineRequest.json
             */
            readonly $schema?: string;
            token: string;
        };
        "Register-proxyRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Register-proxyRequest.json
             */
            readonly $schema?: string;
            sidebarItem?: components["schemas"]["SidebarItem"];
            url: string;
        };
        RestartResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RestartResponseBody.json
             */
            readonly $schema?: string;
            managerUrl: string;
        };
        Role: {
            name: string;
            permissions: ("modules:manage" | "settings:manage" | "settings/users:manage" | "events:manage" | "updates:manage")[] | null;
            title: string;
        };
        Schema: {
            $anchor?: string;
            $comment?: string;
            $defs?: {
                [key: string]: components["schemas"]["Schema"];
            };
            $dynamicRef?: string;
            $id?: string;
            $ref?: string;
            $schema?: string;
            additionalProperties?: components["schemas"]["Schema"];
            allOf?: components["schemas"]["Schema"][] | null;
            anyOf?: components["schemas"]["Schema"][] | null;
            const?: unknown;
            contains?: components["schemas"]["Schema"];
            contentEncoding?: string;
            contentMediaType?: string;
            contentSchema?: components["schemas"]["Schema"];
            default?: unknown;
            dependentRequired?: {
                [key: string]: string[] | null;
            };
            dependentSchemas?: {
                [key: string]: components["schemas"]["Schema"];
            };
            deprecated?: boolean;
            description?: string;
            else?: components["schemas"]["Schema"];
            enum?: unknown[] | null;
            examples?: unknown[] | null;
            /** Format: double */
            exclusiveMaximum?: number;
            /** Format: double */
            exclusiveMinimum?: number;
            format?: string;
            if?: components["schemas"]["Schema"];
            items?: components["schemas"]["Schema"];
            /** Format: int64 */
            maxContains?: number;
            /** Format: double */
            maximum?: number;
            /** Format: int64 */
            maxItems?: number;
            /** Format: int64 */
            maxLength?: number;
            /** Format: int64 */
            maxProperties?: number;
            /** Format: int64 */
            minContains?: number;
            /** Format: double */
            minimum?: number;
            /** Format: int64 */
            minItems?: number;
            /** Format: int64 */
            minLength?: number;
            /** Format: int64 */
            minProperties?: number;
            /** Format: double */
            multipleOf?: number;
            not?: components["schemas"]["Schema"];
            oneOf?: components["schemas"]["Schema"][] | null;
            pattern?: string;
            patternProperties?: {
                [key: string]: components["schemas"]["Schema"];
            };
            prefixItems?: components["schemas"]["Schema"][] | null;
            properties?: components["schemas"]["OrderedMapStringSchema"];
            propertyNames?: components["schemas"]["Schema"];
            readOnly?: boolean;
            required?: string[] | null;
            then?: components["schemas"]["Schema"];
            title?: string;
            type?: string;
            uniqueItems?: boolean;
            writeOnly?: boolean;
        };
        "Set-host-and-portRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Set-host-and-portRequest.json
             */
            readonly $schema?: string;
            host: string;
            /** Format: int64 */
            port: number;
        };
        "Set-user-passwordRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Set-user-passwordRequest.json
             */
            readonly $schema?: string;
            currentPassword: string;
            newPassword: string;
        };
        SidebarItem: {
            category?: string;
            icon: string;
            title: string;
        };
        Theme: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Theme.json
             */
            readonly $schema?: string;
            logoURI?: string;
            smallLogoURI?: string;
            themeOptions: {
                [key: string]: unknown;
            };
        };
        UnapprovedModule: {
            basename: string;
            path: string;
        };
        UpdateInfo: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateInfo.json
             */
            readonly $schema?: string;
            currentVersion: string;
            hasUpdate: boolean;
            latestVersion?: string;
            updatesDisabled?: boolean;
        };
        /** Format: uri */
        URL: string | null;
        UserDetails: {
            role?: components["schemas"]["Role"];
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ChangeUserPasswordRequest = components['schemas']['Change-user-passwordRequest'];
export type ChangeUserRoleRequest = components['schemas']['Change-user-roleRequest'];
export type Config = components['schemas']['Config'];
export type ConfigInput = components['schemas']['ConfigInput'];
export type Cookie = components['schemas']['Cookie'];
export type CreateUserRequest = components['schemas']['Create-userRequest'];
export type DemoLicense = components['schemas']['DemoLicense'];
export type DevelopmentLicense = components['schemas']['DevelopmentLicense'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type ErrorModel = components['schemas']['ErrorModel'];
export type EventInfo = components['schemas']['EventInfo'];
export type GetInfoBody = components['schemas']['GetInfoBody'];
export type GetLicenseResponseBody = components['schemas']['GetLicenseResponseBody'];
export type GetMeBody = components['schemas']['GetMeBody'];
export type GetUsersOutputBody = components['schemas']['GetUsersOutputBody'];
export type Info = components['schemas']['Info'];
export type LicenseClaims = components['schemas']['LicenseClaims'];
export type LicenseV1 = components['schemas']['LicenseV1'];
export type OrderedMapStringSchema = components['schemas']['OrderedMapStringSchema'];
export type PerpetualLicense = components['schemas']['PerpetualLicense'];
export type PostLicenseRequest = components['schemas']['Post-licenseRequest'];
export type PostLoginRequest = components['schemas']['Post-loginRequest'];
export type PostConfigBody = components['schemas']['PostConfigBody'];
export type ProxyOptions = components['schemas']['ProxyOptions'];
export type Queryable = components['schemas']['Queryable'];
export type RegisterOnlineRequest = components['schemas']['Register-onlineRequest'];
export type RegisterProxyRequest = components['schemas']['Register-proxyRequest'];
export type RestartResponseBody = components['schemas']['RestartResponseBody'];
export type Role = components['schemas']['Role'];
export type Schema = components['schemas']['Schema'];
export type SetHostAndPortRequest = components['schemas']['Set-host-and-portRequest'];
export type SetUserPasswordRequest = components['schemas']['Set-user-passwordRequest'];
export type SidebarItem = components['schemas']['SidebarItem'];
export type Theme = components['schemas']['Theme'];
export type UnapprovedModule = components['schemas']['UnapprovedModule'];
export type UpdateInfo = components['schemas']['UpdateInfo'];
export type Url = components['schemas']['URL'];
export type UserDetails = components['schemas']['UserDetails'];
export type $defs = Record<string, never>;
export interface operations {
    "get-appinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-unapproved-appinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnapprovedModule"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "approve-module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "disallow-module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "refresh-appinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "download-backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "restore-backup": {
        parameters: {
            query?: {
                protectExistingConfigs?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/zip": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Config"];
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostConfigBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stop-module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "listen-events": {
        parameters: {
            query?: {
                /** @description Maximum number of past events to include. Only relevant if LastEventID is set to ALL_EVENTS. Limit MAY return fewer events than the limit even if more matching events exists in the database. */
                limit?: number;
                /** @description Events to listen to. If not specified, will return all events. */
                names?: string;
                /** @description Retrieves events raised after this. In RFC3339 format. */
                since?: string;
                /** @description Only returns events from this module ID. Use * to retrieve events regardless of which module ID they are targeting. */
                "target-id"?: string;
                /** @description Only returns events from this module name. Use * to retrieve events regardless of which module name they are targeting. */
                "target-name"?: string;
                /** @description Events to which you will reply. This means emitting an event with reply-to-id set as the ID of the event you receive here. */
                "will-reply"?: string;
            };
            header?: {
                /** @description Type of stream to accept, see the return details for specifications. */
                Accept?: string;
                /** @description Defines which events to retrieve. You may use the special value `ALL_EVENTS` to retrieve all events. */
                "Last-Event-ID"?: string | null;
                /** @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important. */
                "Module-ID"?: string;
                /** @description Name of your module */
                "Module-Name"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    };
                    "application/x-ndjson": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    }[];
                    "text/event-stream": {
                        /** @description The event body. */
                        data?: {
                            /** @description An event's metadata */
                            meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                eventId: string;
                                eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                sourceModuleId?: string;
                                /** @example module-name */
                                sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                targetModuleId?: string;
                                /** @example module-name */
                                targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        id?: string;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "listen-event": {
        parameters: {
            query?: {
                /** @description Maximum number of past events to include. Only relevant if LastEventID is set to ALL_EVENTS. Limit MAY return fewer events than the limit even if more matching events exists in the database. */
                limit?: number;
                /** @description Retrieves events raised after this. In RFC3339 format. */
                since?: string;
                /** @description Only returns events from this module ID. Use * to retrieve events even if they are targetting a specific module. */
                "target-id"?: string;
                /** @description Only returns events from this module name. Use * to retrieve events even if they are targetting a specific module. */
                "target-name"?: string;
                /** @description Indicates you will emit a reply to this event. This means emitting an event with reply-to-id set as the ID of the event you receive here. */
                "will-reply"?: boolean;
            };
            header?: {
                /** @description Type of stream to accept, see the return details for specifications. */
                Accept?: string;
                /** @description Defines which events to retrieve. You may use the special value `ALL_EVENTS` to retrieve all events. */
                "Last-Event-ID"?: string | null;
                /** @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important. */
                "Module-ID"?: string;
                /** @description Name of your module */
                "Module-Name"?: string;
            };
            path: {
                /** @description Event to listen to. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    };
                    "application/x-ndjson": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    }[];
                    "text/event-stream": {
                        /** @description The event body. */
                        data?: {
                            /** @description An event's metadata */
                            meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                eventId: string;
                                eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                sourceModuleId?: string;
                                /** @example module-name */
                                sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                targetModuleId?: string;
                                /** @example module-name */
                                targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        id?: string;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "emit-event": {
        parameters: {
            query?: {
                /** @description When set, the server will keep the connection alive and return any events with the reply ID set to this event. */
                "expect-reply"?: boolean;
                /** @description Marks this event as the reply to another. */
                "reply-to-id"?: string;
                /** @description Only modules with this ID will receive this event. */
                "target-id"?: string;
                /** @description Only modules with this name will receive this event. */
                "target-name"?: string;
            };
            header?: {
                /** @description Type of stream to accept, see the return details for specifications. **Only relevant when expect-reply is set.** */
                Accept?: string;
                /** @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important. */
                "Module-ID"?: string;
                /** @description Name of your module */
                "Module-Name"?: string;
            };
            path: {
                /** @description Name of event to emit. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    };
                    "application/x-ndjson": {
                        /** @description An event's metadata */
                        meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            eventId: string;
                            eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            sourceModuleId?: string;
                            /** @example module-name */
                            sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            targetModuleId?: string;
                            /** @example module-name */
                            targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            time: string;
                        };
                    }[];
                    "text/event-stream": {
                        /** @description The event body. */
                        data?: {
                            /** @description An event's metadata */
                            meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                eventId: string;
                                eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                sourceModuleId?: string;
                                /** @example module-name */
                                sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                targetModuleId?: string;
                                /** @example module-name */
                                targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        id?: string;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInfoBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-update-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateInfo"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-latest-installer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLicenseResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Post-licenseRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register-onlineRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-license-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Post-loginRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "fabric-user"?: components["schemas"]["Cookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-user-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "fabric-user"?: components["schemas"]["Cookie"];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Set-user-passwordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-proxy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register-proxyRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    restart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "refresh-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "fabric-user"?: components["schemas"]["Cookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-host-and-port": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Set-host-and-portRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUsersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-userRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "change-user-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Change-user-passwordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "change-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Change-user-roleRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
