/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/appinfo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get info about available modules */
        readonly get: operations["get-appinfo"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/appinfo-unapproved": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get info about unapproved modules */
        readonly get: operations["get-unapproved-appinfo"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/appinfo-unapproved/{path}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Approve an unauthorized module */
        readonly post: operations["approve-module"];
        /** Disallow an unauthorized module */
        readonly delete: operations["disallow-module"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/appinfo/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Refresh available modules */
        readonly post: operations["refresh-appinfo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/backup": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Download backup
         * @description Download a snapshot of your system, including module configurations, settings, and past events. Sensitive data will not be included.
         */
        readonly get: operations["download-backup"];
        readonly put?: never;
        /** Restore backup */
        readonly post: operations["restore-backup"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get configs of running modules */
        readonly get: operations["get-configs"];
        readonly put?: never;
        /** Add or update a module */
        readonly post: operations["set-config"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/config/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Delete a module */
        readonly delete: operations["delete-module"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/config/{id}/start": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Start a module */
        readonly post: operations["start-module"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/config/{id}/stop": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Stop a module */
        readonly post: operations["stop-module"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/events/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Listen to events */
        readonly get: operations["listen-events"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/events/{name}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Listen to a specific event */
        readonly get: operations["listen-event"];
        readonly put?: never;
        /**
         * Emit event
         * @description Emit an event and optionally open a stream to listen for a response.
         */
        readonly post: operations["emit-event"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/info": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get info about the manager */
        readonly get: operations["get-info"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/info/changelog": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get changelog */
        readonly get: operations["get-changelog"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/info/theme": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get theming data */
        readonly get: operations["get-theme"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/license": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get the current license */
        readonly get: operations["get-license"];
        readonly put?: never;
        /** Register a license */
        readonly post: operations["post-license"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/license/request": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get a license request file */
        readonly get: operations["get-license-request"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Log in */
        readonly post: operations["post-login"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Log out */
        readonly post: operations["post-logout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get current user info */
        readonly get: operations["get-me"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/me/password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Set current user password */
        readonly put: operations["set-user-password"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/proxies/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Register proxy */
        readonly post: operations["register-proxy"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/restart": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Restart */
        readonly post: operations["restart"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/session/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Refresh session */
        readonly post: operations["refresh-session"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/settings/url": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Set host and port */
        readonly post: operations["set-host-and-port"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/users": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get users */
        readonly get: operations["get-users"];
        readonly put?: never;
        /** Create user */
        readonly post: operations["create-user"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/users/{username}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Delete user */
        readonly delete: operations["delete-user"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/users/{username}/password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Change user password */
        readonly put: operations["change-user-password"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/users/{username}/role": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Change user role */
        readonly put: operations["change-user-role"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly "Change-user-passwordRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Change-user-passwordRequest.json
             */
            readonly $schema?: string;
            readonly newPassword: string;
        };
        readonly "Change-user-roleRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Change-user-roleRequest.json
             */
            readonly $schema?: string;
            readonly role: string;
        };
        readonly Config: {
            readonly config?: {
                readonly [key: string]: unknown;
            };
            readonly configSecrets?: readonly string[] | null;
            readonly description?: string;
            readonly disabled?: boolean;
            readonly id: string;
            readonly isOnline: boolean;
            readonly module: string;
            readonly proxy?: components["schemas"]["ProxyOptions"];
            readonly running: boolean;
            readonly service?: boolean;
            readonly statusReason: string;
            readonly title?: string;
        };
        readonly ConfigInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ConfigInput.json
             */
            readonly $schema?: string;
            readonly config: {
                readonly [key: string]: unknown;
            };
            readonly description?: string;
            readonly id?: string;
            readonly module: string;
            readonly title?: string;
        };
        readonly "Create-userRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-userRequest.json
             */
            readonly $schema?: string;
            readonly password: string;
            readonly role: string;
            readonly username: string;
        };
        readonly DemoLicense: {
            /** Format: date-time */
            readonly expiry: string;
        };
        readonly DevelopmentLicense: {
            /** Format: date-time */
            readonly expiry: string;
        };
        readonly ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            readonly location?: string;
            /** @description Error message text */
            readonly message?: string;
            /** @description The value at the given location */
            readonly value?: unknown;
        };
        readonly ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            readonly detail?: string;
            /** @description Optional list of individual error details */
            readonly errors?: readonly components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            readonly instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            readonly status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            readonly title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            readonly type: string;
        };
        readonly EventInfo: {
            readonly $anchor?: string;
            readonly $comment?: string;
            readonly $defs?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly $dynamicRef?: string;
            readonly $id?: string;
            readonly $ref?: string;
            readonly $schema?: string;
            readonly additionalProperties?: components["schemas"]["Schema"];
            readonly allOf?: readonly components["schemas"]["Schema"][] | null;
            readonly anyOf?: readonly components["schemas"]["Schema"][] | null;
            readonly const?: unknown;
            readonly contains?: components["schemas"]["Schema"];
            readonly contentEncoding?: string;
            readonly contentMediaType?: string;
            readonly contentSchema?: components["schemas"]["Schema"];
            readonly default?: unknown;
            readonly dependentRequired?: {
                readonly [key: string]: readonly string[] | null;
            };
            readonly dependentSchemas?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly deprecated?: boolean;
            readonly description?: string;
            readonly else?: components["schemas"]["Schema"];
            readonly enum?: readonly unknown[] | null;
            readonly examples?: readonly unknown[] | null;
            /** Format: double */
            readonly exclusiveMaximum?: number;
            /** Format: double */
            readonly exclusiveMinimum?: number;
            readonly format?: string;
            readonly if?: components["schemas"]["Schema"];
            readonly items?: components["schemas"]["Schema"];
            /** Format: int64 */
            readonly maxContains?: number;
            /** Format: double */
            readonly maximum?: number;
            /** Format: int64 */
            readonly maxItems?: number;
            /** Format: int64 */
            readonly maxLength?: number;
            /** Format: int64 */
            readonly maxProperties?: number;
            /** Format: int64 */
            readonly minContains?: number;
            /** Format: double */
            readonly minimum?: number;
            /** Format: int64 */
            readonly minItems?: number;
            /** Format: int64 */
            readonly minLength?: number;
            /** Format: int64 */
            readonly minProperties?: number;
            /** Format: double */
            readonly multipleOf?: number;
            readonly name: string;
            readonly not?: components["schemas"]["Schema"];
            readonly oneOf?: readonly components["schemas"]["Schema"][] | null;
            readonly pattern?: string;
            readonly patternProperties?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly prefixItems?: readonly components["schemas"]["Schema"][] | null;
            readonly properties?: components["schemas"]["OrderedMapStringSchema"];
            readonly propertyNames?: components["schemas"]["Schema"];
            readonly readOnly?: boolean;
            readonly reply?: components["schemas"]["Schema"];
            readonly required?: readonly string[] | null;
            readonly then?: components["schemas"]["Schema"];
            readonly title?: string;
            readonly type?: string;
            readonly uniqueItems?: boolean;
            readonly writeOnly?: boolean;
        };
        readonly GetInfoBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetInfoBody.json
             */
            readonly $schema?: string;
            readonly accessFromLoopback: boolean;
            readonly managerHost: string;
            /** Format: int64 */
            readonly managerPort: number;
            readonly showInitialiseFlow: boolean;
            readonly version: string;
        };
        readonly GetLicenseResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetLicenseResponseBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            readonly configuredModules?: number;
            /** Format: date-time */
            readonly expiry?: string;
            readonly license?: components["schemas"]["LicenseClaims"];
            readonly licenseError?: string;
            readonly licenseWarning?: string;
            readonly shortError?: string;
        };
        readonly GetMeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetMeBody.json
             */
            readonly $schema?: string;
            readonly permissions?: readonly ("settings:manage" | "settings/users:manage" | "modules:manage")[] | null;
            readonly role: string;
            readonly username: string;
        };
        readonly GetUsersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetUsersOutputBody.json
             */
            readonly $schema?: string;
            readonly users: readonly components["schemas"]["UserDetails"][] | null;
        };
        readonly Info: {
            readonly config?: components["schemas"]["Schema"];
            readonly description?: string;
            readonly emits?: readonly components["schemas"]["EventInfo"][] | null;
            readonly listens?: readonly components["schemas"]["EventInfo"][] | null;
            readonly name: string;
            readonly queries?: readonly components["schemas"]["Queryable"][] | null;
            readonly service?: boolean;
            readonly title: string;
            readonly version?: string;
        };
        readonly LicenseClaims: {
            readonly id: string;
            /** Format: date-time */
            readonly issued: string;
            readonly v1?: components["schemas"]["LicenseV1"];
            /** Format: int64 */
            readonly version: number;
        };
        readonly LicenseV1: {
            readonly demo?: components["schemas"]["DemoLicense"];
            readonly development?: components["schemas"]["DevelopmentLicense"];
            readonly hardwareId: string;
            readonly perpetual?: components["schemas"]["PerpetualLicense"];
            readonly storedToken: string;
        };
        readonly OrderedMapStringSchema: Record<string, never>;
        readonly PerpetualLicense: {
            /** Format: int64 */
            readonly configuredModuleLimit: number;
            /** Format: date-time */
            readonly supportExpiry: string;
        };
        readonly "Post-licenseRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Post-licenseRequest.json
             */
            readonly $schema?: string;
            readonly license: string;
        };
        readonly "Post-loginRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Post-loginRequest.json
             */
            readonly $schema?: string;
            readonly password: string;
            readonly username: string;
        };
        readonly PostConfigBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostConfigBody.json
             */
            readonly $schema?: string;
            readonly id: string;
        };
        readonly ProxyOptions: {
            readonly sidebarItem?: components["schemas"]["SidebarItem"];
            readonly url: components["schemas"]["URL"];
        };
        readonly Queryable: {
            readonly description?: string;
            readonly input?: components["schemas"]["Schema"];
            readonly mediaType: string;
            readonly name: string;
            readonly title?: string;
        };
        readonly "Register-proxyRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Register-proxyRequest.json
             */
            readonly $schema?: string;
            readonly sidebarItem?: components["schemas"]["SidebarItem"];
            readonly url: string;
        };
        readonly RestartResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RestartResponseBody.json
             */
            readonly $schema?: string;
            readonly managerUrl: string;
        };
        readonly Role: {
            readonly name: string;
            readonly permissions: readonly ("settings:manage" | "settings/users:manage" | "modules:manage")[] | null;
            readonly title: string;
        };
        readonly Schema: {
            readonly $anchor?: string;
            readonly $comment?: string;
            readonly $defs?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly $dynamicRef?: string;
            readonly $id?: string;
            readonly $ref?: string;
            readonly $schema?: string;
            readonly additionalProperties?: components["schemas"]["Schema"];
            readonly allOf?: readonly components["schemas"]["Schema"][] | null;
            readonly anyOf?: readonly components["schemas"]["Schema"][] | null;
            readonly const?: unknown;
            readonly contains?: components["schemas"]["Schema"];
            readonly contentEncoding?: string;
            readonly contentMediaType?: string;
            readonly contentSchema?: components["schemas"]["Schema"];
            readonly default?: unknown;
            readonly dependentRequired?: {
                readonly [key: string]: readonly string[] | null;
            };
            readonly dependentSchemas?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly deprecated?: boolean;
            readonly description?: string;
            readonly else?: components["schemas"]["Schema"];
            readonly enum?: readonly unknown[] | null;
            readonly examples?: readonly unknown[] | null;
            /** Format: double */
            readonly exclusiveMaximum?: number;
            /** Format: double */
            readonly exclusiveMinimum?: number;
            readonly format?: string;
            readonly if?: components["schemas"]["Schema"];
            readonly items?: components["schemas"]["Schema"];
            /** Format: int64 */
            readonly maxContains?: number;
            /** Format: double */
            readonly maximum?: number;
            /** Format: int64 */
            readonly maxItems?: number;
            /** Format: int64 */
            readonly maxLength?: number;
            /** Format: int64 */
            readonly maxProperties?: number;
            /** Format: int64 */
            readonly minContains?: number;
            /** Format: double */
            readonly minimum?: number;
            /** Format: int64 */
            readonly minItems?: number;
            /** Format: int64 */
            readonly minLength?: number;
            /** Format: int64 */
            readonly minProperties?: number;
            /** Format: double */
            readonly multipleOf?: number;
            readonly not?: components["schemas"]["Schema"];
            readonly oneOf?: readonly components["schemas"]["Schema"][] | null;
            readonly pattern?: string;
            readonly patternProperties?: {
                readonly [key: string]: components["schemas"]["Schema"];
            };
            readonly prefixItems?: readonly components["schemas"]["Schema"][] | null;
            readonly properties?: components["schemas"]["OrderedMapStringSchema"];
            readonly propertyNames?: components["schemas"]["Schema"];
            readonly readOnly?: boolean;
            readonly required?: readonly string[] | null;
            readonly then?: components["schemas"]["Schema"];
            readonly title?: string;
            readonly type?: string;
            readonly uniqueItems?: boolean;
            readonly writeOnly?: boolean;
        };
        readonly "Set-host-and-portRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Set-host-and-portRequest.json
             */
            readonly $schema?: string;
            readonly host: string;
            /** Format: int64 */
            readonly port: number;
        };
        readonly "Set-user-passwordRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Set-user-passwordRequest.json
             */
            readonly $schema?: string;
            readonly currentPassword: string;
            readonly newPassword: string;
        };
        readonly SidebarItem: {
            readonly category?: string;
            readonly icon: string;
            readonly title: string;
        };
        readonly Theme: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Theme.json
             */
            readonly $schema?: string;
            readonly logoURI?: string;
            readonly smallLogoURI?: string;
            readonly themeOptions: {
                readonly [key: string]: unknown;
            };
        };
        readonly UnapprovedModule: {
            readonly basename: string;
            readonly path: string;
        };
        /** Format: uri */
        readonly URL: string | null;
        readonly UserDetails: {
            readonly role?: components["schemas"]["Role"];
            readonly username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ChangeUserPasswordRequest = components['schemas']['Change-user-passwordRequest'];
export type ChangeUserRoleRequest = components['schemas']['Change-user-roleRequest'];
export type Config = components['schemas']['Config'];
export type ConfigInput = components['schemas']['ConfigInput'];
export type CreateUserRequest = components['schemas']['Create-userRequest'];
export type DemoLicense = components['schemas']['DemoLicense'];
export type DevelopmentLicense = components['schemas']['DevelopmentLicense'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type ErrorModel = components['schemas']['ErrorModel'];
export type EventInfo = components['schemas']['EventInfo'];
export type GetInfoBody = components['schemas']['GetInfoBody'];
export type GetLicenseResponseBody = components['schemas']['GetLicenseResponseBody'];
export type GetMeBody = components['schemas']['GetMeBody'];
export type GetUsersOutputBody = components['schemas']['GetUsersOutputBody'];
export type Info = components['schemas']['Info'];
export type LicenseClaims = components['schemas']['LicenseClaims'];
export type LicenseV1 = components['schemas']['LicenseV1'];
export type OrderedMapStringSchema = components['schemas']['OrderedMapStringSchema'];
export type PerpetualLicense = components['schemas']['PerpetualLicense'];
export type PostLicenseRequest = components['schemas']['Post-licenseRequest'];
export type PostLoginRequest = components['schemas']['Post-loginRequest'];
export type PostConfigBody = components['schemas']['PostConfigBody'];
export type ProxyOptions = components['schemas']['ProxyOptions'];
export type Queryable = components['schemas']['Queryable'];
export type RegisterProxyRequest = components['schemas']['Register-proxyRequest'];
export type RestartResponseBody = components['schemas']['RestartResponseBody'];
export type Role = components['schemas']['Role'];
export type Schema = components['schemas']['Schema'];
export type SetHostAndPortRequest = components['schemas']['Set-host-and-portRequest'];
export type SetUserPasswordRequest = components['schemas']['Set-user-passwordRequest'];
export type SidebarItem = components['schemas']['SidebarItem'];
export type Theme = components['schemas']['Theme'];
export type UnapprovedModule = components['schemas']['UnapprovedModule'];
export type Url = components['schemas']['URL'];
export type UserDetails = components['schemas']['UserDetails'];
export type $defs = Record<string, never>;
export interface operations {
    readonly "get-appinfo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Info"][] | null;
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-unapproved-appinfo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["UnapprovedModule"][] | null;
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "approve-module": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly path: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "disallow-module": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly path: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "refresh-appinfo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "download-backup": {
        readonly parameters: {
            readonly query?: {
                readonly excludeEvents?: boolean;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly "Content-Disposition"?: string;
                    readonly "Content-Length"?: number;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": string;
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "restore-backup": {
        readonly parameters: {
            readonly query?: {
                readonly protectExistingConfigs?: boolean;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/zip": string;
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-configs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: components["schemas"]["Config"];
                    };
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "set-config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ConfigInput"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PostConfigBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "delete-module": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "start-module": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "stop-module": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "listen-events": {
        readonly parameters: {
            readonly query?: {
                /** @description Maximum number of past events to include. Only relevant if LastEventID is set to ALL_EVENTS. Limit MAY return fewer events than the limit even if more matching events exists in the database. */
                readonly limit?: number;
                /**
                 * @description Events to listen to. If not specified, will return all events.
                 * @example test-event,test-event2
                 */
                readonly names?: string;
                /**
                 * @description Retrieves events raised after this. In RFC3339 format.
                 * @example 1985-04-12T23:20:50.52Z
                 */
                readonly since?: string;
                /**
                 * @description Only returns events from this module ID. Use * to retrieve events regardless of which module ID they are targeting.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "target-id"?: string;
                /**
                 * @description Only returns events from this module name. Use * to retrieve events regardless of which module name they are targeting.
                 * @example module-name
                 */
                readonly "target-name"?: string;
                /**
                 * @description Events to which you will reply. This means emitting an event with reply-to-id set as the ID of the event you receive here.
                 * @example test-event,test-event2
                 */
                readonly "will-reply"?: string;
            };
            readonly header?: {
                /**
                 * @description Type of stream to accept, see the return details for specifications.
                 * @example application/x-ndjson,text/event-stream
                 */
                readonly Accept?: string;
                /** @description Defines which events to retrieve. You may use the special value `ALL_EVENTS` to retrieve all events. */
                readonly "Last-Event-ID"?: string | null;
                /**
                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "Module-ID"?: string;
                /** @description Name of your module */
                readonly "Module-Name"?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Stream established */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    };
                    readonly "application/x-ndjson": readonly {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    }[];
                    readonly "text/event-stream": readonly {
                        /** @description The event body. */
                        readonly data?: {
                            /** @description An event's metadata */
                            readonly meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly eventId: string;
                                readonly eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly sourceModuleId?: string;
                                /** @example module-name */
                                readonly sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly targetModuleId?: string;
                                /** @example module-name */
                                readonly targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                readonly time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        readonly event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        readonly id?: string;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    }[];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "listen-event": {
        readonly parameters: {
            readonly query?: {
                /** @description Maximum number of past events to include. Only relevant if LastEventID is set to ALL_EVENTS. Limit MAY return fewer events than the limit even if more matching events exists in the database. */
                readonly limit?: number;
                /**
                 * @description Retrieves events raised after this. In RFC3339 format.
                 * @example 1985-04-12T23:20:50.52Z
                 */
                readonly since?: string;
                /**
                 * @description Only returns events from this module ID. Use * to retrieve events even if they are targetting a specific module.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "target-id"?: string;
                /**
                 * @description Only returns events from this module name. Use * to retrieve events even if they are targetting a specific module.
                 * @example module-name
                 */
                readonly "target-name"?: string;
                /** @description Indicates you will emit a reply to this event. This means emitting an event with reply-to-id set as the ID of the event you receive here. */
                readonly "will-reply"?: boolean;
            };
            readonly header?: {
                /**
                 * @description Type of stream to accept, see the return details for specifications.
                 * @example application/x-ndjson,text/event-stream
                 */
                readonly Accept?: string;
                /** @description Defines which events to retrieve. You may use the special value `ALL_EVENTS` to retrieve all events. */
                readonly "Last-Event-ID"?: string | null;
                /**
                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "Module-ID"?: string;
                /** @description Name of your module */
                readonly "Module-Name"?: string;
            };
            readonly path: {
                /**
                 * @description Event to listen to.
                 * @example test-event
                 */
                readonly name: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Stream established */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    };
                    readonly "application/x-ndjson": readonly {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    }[];
                    readonly "text/event-stream": readonly {
                        /** @description The event body. */
                        readonly data?: {
                            /** @description An event's metadata */
                            readonly meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly eventId: string;
                                readonly eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly sourceModuleId?: string;
                                /** @example module-name */
                                readonly sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly targetModuleId?: string;
                                /** @example module-name */
                                readonly targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                readonly time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        readonly event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        readonly id?: string;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    }[];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "emit-event": {
        readonly parameters: {
            readonly query?: {
                /** @description When set, the server will keep the connection alive and return any events with the reply ID set to this event. */
                readonly "expect-reply"?: boolean;
                /** @description Marks this event as the reply to another. */
                readonly "reply-to-id"?: string;
                /**
                 * @description Only modules with this ID will receive this event.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "target-id"?: string;
                /**
                 * @description Only modules with this name will receive this event.
                 * @example module-name
                 */
                readonly "target-name"?: string;
            };
            readonly header?: {
                /**
                 * @description Type of stream to accept, see the return details for specifications. **Only relevant when expect-reply is set.**
                 * @example application/x-ndjson,text/event-stream
                 */
                readonly Accept?: string;
                /**
                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                 */
                readonly "Module-ID"?: string;
                /** @description Name of your module */
                readonly "Module-Name"?: string;
            };
            readonly path: {
                /**
                 * @description Name of event to emit.
                 * @example test-event
                 */
                readonly name: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly [key: string]: unknown;
                };
            };
        };
        readonly responses: {
            /** @description Stream established */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    };
                    readonly "application/x-ndjson": readonly {
                        /** @description An event's metadata */
                        readonly meta: {
                            /**
                             * @description The ID of this event as UUIDv4.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly eventId: string;
                            readonly eventName: string;
                            /**
                             * @description The ID of another event that this one is a reply to.
                             * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                             */
                            readonly replyToId?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly sourceModuleId?: string;
                            /** @example module-name */
                            readonly sourceModuleName?: string;
                            /**
                             * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                             * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                             */
                            readonly targetModuleId?: string;
                            /** @example module-name */
                            readonly targetModuleName?: string;
                            /**
                             * Format: date-time
                             * @example 1985-04-12T23:20:50.52Z
                             */
                            readonly time: string;
                        };
                    }[];
                    readonly "text/event-stream": readonly {
                        /** @description The event body. */
                        readonly data?: {
                            /** @description An event's metadata */
                            readonly meta: {
                                /**
                                 * @description The ID of this event as UUIDv4.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly eventId: string;
                                readonly eventName: string;
                                /**
                                 * @description The ID of another event that this one is a reply to.
                                 * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                                 */
                                readonly replyToId?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly sourceModuleId?: string;
                                /** @example module-name */
                                readonly sourceModuleName?: string;
                                /**
                                 * @description A module's unique identifier. UUIDv4 should be used when the identity of a module is not important.
                                 * @example a036c3be-3f9e-461d-8913-78709cd7e8a4
                                 */
                                readonly targetModuleId?: string;
                                /** @example module-name */
                                readonly targetModuleName?: string;
                                /**
                                 * Format: date-time
                                 * @example 1985-04-12T23:20:50.52Z
                                 */
                                readonly time: string;
                            };
                        };
                        /**
                         * @deprecated
                         * @description The event name. Deprecated because EventSource doesn't allow reading all messages. Use the `meta.eventName` field instead.
                         */
                        readonly event?: string;
                        /**
                         * @description The event ID.
                         * @example 0c780f99-8fdd-42b9-a936-1650aa95f6c8
                         */
                        readonly id?: string;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    }[];
                };
            };
            /** @description No content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-info": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetInfoBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-changelog": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": string;
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-theme": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Theme"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-license": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetLicenseResponseBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "post-license": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Post-licenseRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-license-request": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": string;
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "post-login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Post-loginRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "post-logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: {
                readonly "fabric-user"?: string;
            };
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetMeBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "set-user-password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: {
                readonly "fabric-user"?: string;
            };
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Set-user-passwordRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "register-proxy": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Register-proxyRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly restart: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "refresh-session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: {
                readonly "fabric-user"?: string;
            };
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "set-host-and-port": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Set-host-and-portRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RestartResponseBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "get-users": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetUsersOutputBody"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "create-user": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Create-userRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "delete-user": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly username: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "change-user-password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly username: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Change-user-passwordRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    readonly "change-user-role": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly username: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["Change-user-roleRequest"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
