on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --access public
