on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write
  issues: write # For labels

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
